# Generated by Django 4.2.6 on 2023-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_category_owner_recipient_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='почта'),
        ),
    ]
