# Generated by Django 4.2.6 on 2023-10-11 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
        ('mailsender', '0003_alter_mail_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='category',
            field=models.ManyToManyField(to='recipients.category', verbose_name='категория получателей'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 11, 16, 22, 12, 227376, tzinfo=datetime.timezone.utc), verbose_name='дата отправки (старта)'),
        ),
    ]
