# Generated by Django 4.2.6 on 2023-10-11 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0005_alter_mail_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 11, 16, 54, 3, 814199, tzinfo=datetime.timezone.utc), verbose_name='дата отправки (старта)'),
        ),
    ]
