# Generated by Django 4.2.6 on 2023-10-11 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0006_alter_mail_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата отправки (старта)'),
        ),
    ]
