# Generated by Django 4.2.6 on 2023-10-13 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0008_mail_owner_message_owner_try_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
