# Generated by Django 4.2.6 on 2023-10-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0009_mail_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата завершения'),
        ),
    ]
